# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e7f25fa8ba9dc33e699e1d907cdf9914797e41f0bdbeb9fad7dc1fc2f2e39aae8dc501d6b24e8120c113ed95e00fb88bbde72b05ce578f346eed0782df72dcb

test:
  secret_key_base: c1f4bb13a4c51a2df512360a5f4fb6748bf6232e4a4e2184cd8a5702fa4b626ac45a61325e5a756cb04668c34ca9f06914105515a1c979a1fb68b42109d7b57e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
